# Generated by Django 6.1.1 on 2026-09-14 08:41

import django.db.models.deletion
import django.utils.timezone
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMatchGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('mode', models.CharField(choices=[('restaurants', 'Restaurants'), ('dishes', 'Dishes')], default='restaurants', max_length=16)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('swiping', 'Swiping'), ('completed', 'Completed')], db_index=True, default='lobby', max_length=16)),
                ('area_name', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=24)),
                ('is_host', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('joined', 'Joined'), ('swiping', 'Swiping'), ('finished', 'Finished')], default='joined', max_length=16)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.foodmatchgroup')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(db_index=True, max_length=128)),
                ('direction', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass')], max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.participant')),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=128)),
                ('position', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='api.foodmatchgroup')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['group', 'position'], name='api_deckcar_group_i_71961d_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'card_id'), name='unique_card_per_group')],
            },
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('group', 'display_name'), name='unique_display_name_per_group'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['participant', 'card_id'], name='api_vote_partici_4b24e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('participant', 'card_id'), name='unique_vote_per_card'),
        ),
    ]
